apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}-service
  labels:
    app.kubernetes.io/name: {{ include "service.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "service.fullname" . }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}