---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.roleArns.albController }}"
  name: aws-load-balancer-controller
  namespace: aws-load-balancer-controller-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.roleArns.gatewayController }}"
  name: gateway-api-controller
  namespace: aws-application-networking-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.roleArns.ebsCsiController }}"
  name: ebs-csi-controller-sa
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.roleArns.adotCollector }}"
  name: adot-collector
  namespace: fargate-container-insights