#cloud-config
write_files:
  - path: /etc/yum.repos.d/mongodb-org-8.2.repo
    content: |
      [mongodb-org-8.2]
      name=MongoDB Repository
      baseurl=https://repo.mongodb.org/yum/amazon/2023/mongodb-org/8.2/x86_64/
      gpgcheck=1
      enabled=1
      gpgkey=https://pgp.mongodb.com/server-8.0.asc

runcmd:
  - yum install -y mongodb-org
  - cp /etc/mongod.conf /etc/mongos.conf
  - sed -i 's/#port: 27017/port: 27017/' /etc/mongos.conf
  - sed -i 's/bindIp: 127.0.0.1/bindIp: 0.0.0.0/' /etc/mongos.conf
  - echo 'sharding:' >> /etc/mongos.conf
  - echo '  configDB: configReplSet/config0:27019,config1:27019,config2:27019' >> /etc/mongos.conf
  - systemctl enable mongos
  - systemctl restart mongos